package com.example.website.models;

public enum Problem {
    AGING_IN_PLACE,
    POST_HOSPITAL_RECOVERY,
    DISABILITY_SUPPORT,
    DEMENTIA_CARE,
    CHRONIC_DISEASE_MANAGEMENT,
    RESPITE_CARE,
    HOUSEWORK_AND_ERRANDS,
    COMPANIONSHIP,
    END_OF_LIFE_CARE,
    MATERNITY_SUPPORT
}
